version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: spring-batch-postgres
    environment:
      POSTGRES_DB: spring_batch
      POSTGRES_USER: spring
      POSTGRES_PASSWORD: spring
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
